config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :products do
    resources :orders, only: [:create]
  end


  resources :orders, only: [:index, :update, :destroy]
  get '/my_products', to: "products#my_products"
  post 'checkout', to: 'orders#purchase', as: 'purchase'
  get 'confirmation', to: 'orders#confirmation'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
  # validates :delivery_address, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders, dependent: :destroy
  include PgSearch::Model

  belongs_to :user
  has_one_attached :photo
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_float: true }
  validates :quantity, presence: true, numericality: { only_integer: true }

  pg_search_scope :search_by_title_and_syllabus,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :destroy]

  def show
    @order = Order.new
  end

  def purchase
    @orders = current_user.orders.where(purchased: false)
    @orders.each do |order|
      order.purchased = true
      order.save!
    end
    redirect_to confirmation_path
  end

  def index
    @orders = current_user.orders.where(purchased: false)
  end

  def confirmation

  end

  def new
    @product = Product.find(params[:product_id])
    @order = Order.new
  end

  def create
    @product = Product.find(params[:product_id])
    @order = Order.new
    @order.product = @product
    @order.user = current_user
    @order.purchased = false


    if @product.quantity.positive? && @order.save
      @product.quantity -= 1
      @product.save
      redirect_to orders_path
    else
      render 'products/show'
    end
  end

  def destroy
    @order.destroy
    redirect_to products_path(@order.product)
  end

  private

  def order_params
    params.require(:product).permit(:delivery_address, :user_id, :product_id)
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home

    products = Product.all
    @latest = products.last(4)
    @top = products.sort_by { |product| product.orders.count }.last(4).reverse
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present? && user_signed_in?
      sql_query = " \
        products.name @@ :query \
        OR products.description @@ :query \
      "
      @query = Product.where(sql_query, query: "%#{params[:query]}%")
      @products = @query.where.not(quantity: 0) - current_user.products

    elsif params[:query].present?
      sql_query = " \
        products.name @@ :query \
        OR products.description @@ :query \
      "
      @query = Product.where(sql_query, query: "%#{params[:query]}%")
      @products = @query.where.not(quantity: 0)

    else
      @products = Product.where.not(quantity: 0)
    end
  end

  def my_products
    @products = current_user.products
  end

  def show
    if user_signed_in?
      @products = current_user.products
    end
    @order = Order.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.save
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def destroy
    @product.destroy
    redirect_to my_products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :quantity, :photo)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>homemade</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= yield :custom_css %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/orders/checkout.html.erb
<% content_for :custom_css do %>
  <style>
    body {
      background-color: white;
    }
  </style>
<% end %>
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <h1 class="border-bottom">My Shopping Cart</h1>
      <h2>Total items: <%= @orders.size %></h2>
      <% @orders.each do |order| %>
        <div class="d-flex border-bottom mb-4">
          <div class="mr-4">
            <%= cl_image_tag order.product.photo.key, width: 100, height: 100, crop: :fill, class: 'img-fluid mb-4' %>
          </div>
          <div>
            <h3><%= order.product.name %> | $ <%= order.product.price %></h3>
          </div>
        </div>
      <% end %>
      <%= link_to 'Continue shopping', products_path, class: 'btn btn-secondary' %>
      <%= link_to 'Confirm Purchase', confirmation_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/orders/checkout_message.html.erb
<div class="container my-4">
  <h1>Contratulations, your order was sucessfully received!</h1>
  <h2>You will get an e-mail at <%= current_user.email %> with further details.</h2>

  <%= link_to 'Continue shopping', products_path, class: 'btn btn-secondary' %>

</div>

app/views/orders/confirmation.html.erb
<div class="container my-4">
  <h1>Contratulations, your order was sucessfully received!</h1>
  <h2>You will get an e-mail at <%= current_user.email %> with further details.</h2>

  <%= link_to 'Continue shopping', products_path, class: 'btn btn-secondary' %>

</div>

app/views/orders/index.html.erb
<% content_for :custom_css do %>
  <style>
    body {
      background-color: white;
    }
  </style>
<% end %>
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <h1 class="border-bottom">My Shopping Cart</h1>
      <h2>Total items: <%= @orders.size %></h2>
      <% @orders.each do |order| %>
        <div class="d-flex border-bottom mb-4">
          <div class="mr-4">
            <%= cl_image_tag order.product.photo.key, width: 100, height: 100, crop: :fill, class: 'img-fluid mb-4' %>
          </div>
          <div>
            <h3><%= order.product.name %> | $ <%= order.product.price %></h3>
          </div>
        </div>
      <% end %>
      <%= link_to 'Continue shopping', products_path, class: 'btn btn-secondary' %>
      <% if @orders.size.positive? %>
      <%= link_to 'Confirm Purchase', purchase_path, method: 'post', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">

  <div class="row d-flex justify-content-end">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <%= form_tag products_path, class: 'input-group mb-3', method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find Product"
      %>
      <div class="input-group-append">
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div id="carouselExampleSlidesOnly" class="carousel slide mb-4" data-ride="carousel" data-interval="3000">
        <div class="carousel-inner banner">
          <div class="carousel-item active">
            <%= image_tag("newbanner1.jpg", class: "img-fluid w-100") %>
          </div>
          <div class="carousel-item">
            <%= image_tag("newbanner2.jpg",class: "img-fluid w-100" ) %>
          </div>
          <div class="carousel-item">
            <%= image_tag("newbanner3.jpg",class: "img-fluid w-100" ) %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">

      <h1 class="bg-primary text-center mb-4"><span class="badge badge-primary">Latest products</span></h1>
      <div class="row">

      <% @latest.each do |product| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">

        <div class="card">
            <%= cl_image_tag(product.photo.key, height: 300, width: 400, crop: :fill, class: 'img-fluid') %>
          <div class="card-body">

            <h2><%= truncate product.name, length: 18 %></h2>
            <p>$ <%= product.price %></p>
            <%= link_to 'Buy <i class="fas fa-shopping-cart"></i>'.html_safe, product_path(product), class: 'btn btn-primary' %>
          </div>
        </div>

      </div>
      <% end %>

      </div>

    </div>
  </div>
  <div class="row">
    <div class="col-12">

      <h1 class="bg-primary text-center mb-4"><span class="badge badge-primary">Most Popular</span></h1>
      <div class="row">

      <% @top.each do |product| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">

        <div class="card">
            <%= cl_image_tag(product.photo.key, height: 300, width: 400, crop: :fill, class: 'img-fluid') %>
          <div class="card-body">
            <h2><%= truncate product.name, length: 18 %></h2>
            <p>$ <%= product.price %></p>
            <%= link_to 'Buy <i class="fas fa-shopping-cart"></i>'.html_safe, product_path(product), class: 'btn btn-primary'%>

          </div>
        </div>

      </div>
       <h1 class="bg-secondary text-center mb-4"><span class="badge badge-secondary"></span></h1>
      <% end %>

      </div>

    </div>
  </div>
</div>

<div></div>

app/views/products/index.html.erb
<div class="container my-4">
  <div class="row pt-2">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-8">
      <h1>All Products</h1>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <%= form_tag products_path, class: 'input-group mb-3', method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find Product"
      %>
      <div class="input-group-append">
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <% @products.each do |product| %>
      <div class="col-lg-3">
        <div class="card rounded my-4">
          <%= cl_image_tag product.photo.key, width: 640, height: 640, crop: :fill, class: 'img-fluid' %>
          <div class="card-body">
            <h2 class="card-title"><%= link_to product.name, product_path(product) %></h2>
            <%= link_to 'Buy <i class="fas fa-shopping-cart"></i>'.html_safe, product_path(product), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/my_products.html.erb
<div class="container my-4">
  <div class="row pt-2">
    <div class="col-12">
      <h1>My Products</h1>
    </div>
  </div>

  <% if current_user.products.length >= 1 %>

    <div class="row justify-content-center">
      <% @products.each do |product| %>
        <div class="col-lg-3">
          <div class="card rounded my-4">
            <%= cl_image_tag product.photo.key, width: 640, height: 640, crop: :fill, class: 'img-fluid' %>
            <div class="card-body">
              <h2 class="card-title"><%= link_to product.name, product_path(product) %></h2>
              <%= link_to 'See details', product_path(product), class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  <% else %>

    <div class="row justify-content-center text-center align-items-center">
      <div class="col-lg-6">
        <p>No products yet.</p>
        <%= link_to "Advertise your product", new_product_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>

  <% end %>
</div>

app/views/products/new.html.erb
<div class="container my-4">
  <div class="row justify-content-center align-items-center">
    <div class="col-lg-6">
      <h1>Advertise your product</h1>
      <p>Fill out the information below:</p>
      <%= simple_form_for @product do |f| %>
      <div class="form-group">
        <%= f.input :name, class: 'form-control form-control-lg' %>
      </div>
      <div class="form-group">
        <%= f.input :description, as: :text, class: 'form-control form-control-lg' %>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.input :price, class: 'form-control form-control-lg' %>
        </div>
        <div class="form-group col-md-6">
          <%= f.input :quantity, class: 'form-control form-control-lg' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.input :photo, as: :file %>
      </div>
      <div class="form-group">
        <%= f.submit :submit, class: 'btn btn-lg btn-primary' %>
      </div>
      <% end %>
      <%= link_to 'Back to my products list', my_products_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <!-- Product image -->
      <%= cl_image_tag @product.photo.key, width: 640, height: 640, crop: :fill, class: 'img-fluid mb-4' %>
    </div>
    <div class="col-12 col-md-6">
      <!-- Product info -->
      <h1 class="display-4 border-bottom pb-4 mb-4"><%= @product.name %></h1>
      <p class="lead"><%= @product.description %></p>
      <p>Quantity: <%= @product.quantity %></p>
      <h1><span class="badge badge-light">$ <%= @product.price %></span></h1>
      <% if user_signed_in? && @product.user_id == current_user.id %>
      <%= link_to 'Delete this product', product_path, method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-danger' %>
      <div class="badge badge-warning text-wrap">You're the owner of this product
      </div>
      <% else %>
      <%= link_to 'Buy <i class="fas fa-shopping-cart"></i>'.html_safe, product_orders_path(@product), method: :post, class: 'btn btn-success btn-lg' %>
      <% end %>
      <div class="border-top pt-4 mt-4">
        <% if user_signed_in? && @product.user_id == current_user.id %>
        <%= link_to 'Back to my products list', my_products_path, class: 'btn btn-secondary' %>
        <% elsif %>
        <%= link_to 'Back to products list', products_path, class: 'btn btn-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>


<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
      <div class="footer-copyright">
        Homemade - 2020 - Rua Mourato Coelho - Vila Madalena <i class="fas fa-shopping-cart"></i>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "homemade-logo-green.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Products", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My products", my_products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My orders", orders_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Advertise your product", new_product_path, class: "btn btn-primary round mx-2" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://api.adorable.io/avatars/100/abott@adorable.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "All Products", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>